mkdir build
cd build
echo -DENABLE_OPENMP=OFF -DENABLE_THREADS=OFF -DWITH_COMBINE_THREADS=OFF
cmake -GNinja -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DBUILD_TESTS=OFF -DBUILD_SHARED_LIBS=OFF "-DCMAKE_PREFIX_PATH:STRING=C:/Qt/6.1.2/mingw81_64" ..
cmake --build .